### ISSUE TITLE
What is the license on these?

### ISSUE THREAD

**Issue by keyspace** [THDigi/SE-ModScript-Examples#1]
Hi! I'm using the networking example code, near-verbatim, in [a project](https://github.com/keyspace/Stamina) licensed under Creative Commons BY-NC-SA-4.0. There is attribution and links in the relevant files, as well as in the `README`.

However, I was wondering if this is acceptable.

**Comment by THDigi** [comment]
Yes all the examples are free to use, I should probably add a licence for clarity =)

EDIT: Was thinking about this one: 
https://creativecommons.org/licenses/by-sa/4.0/

But I don't want others' edits to these to not be able to apply NC... so not sure how that works =)

**Comment by keyspace** [comment]
> so not sure how that works =)

IANAL, but that's the thing with "SA" - it forbids further restrictions ([wikipedia](https://en.wikipedia.org/wiki/Creative_Commons_license#Types_of_licenses), see "Share-Alike line in the table; same can be gathered from [CC's own summary](https://creativecommons.org/about/cclicenses/)).

It's somewhat unfortunate that _just_ NC can't be singled out as an allowed further restriction for derivatives, but "oh well".

-----

In my case, NC was a pavlovian reflex, BY+SA was all that was actually needed.

Thankfully, I can stop distributing under the more restrictive license and start with a less restrictive one in just one commit, since everybody (me ;D) agrees, and other people's code is under their own licenses, seemingly permissive.

In fact, I'll do that right now, putting other people's code in the repo and slapping an NC on top is not right.
